# Stage 1: Build the React frontend
FROM node:18 AS build-client
WORKDIR /app/client
COPY client/package.json client/package-lock.json ./
RUN npm install

# Copy the rest of the client code and build it
COPY client ./
RUN npm run build

# Stage 2: Setup the Node.js server
FROM node:18
WORKDIR /app
RUN apt-get update && apt-get install -y build-essential python3 && rm -rf /var/lib/apt/lists/*
COPY server/package.json server/package-lock.json ./
RUN npm install


COPY server ./server  
WORKDIR /app/server
COPY --from=build-client /app/client/build ./public  
EXPOSE 8000

# Start the server
CMD ["npm", "start"]
